version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: weekly

updates:
  - package-ecosystem: uv
    directory: /
    open-pull-requests-limit: 1
    patterns:
      - "*"
    cooldown:
      default-days: 14
    multi-ecosystem-group: all-dependencies

  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 1
    patterns:
      - "*"
    cooldown:
      default-days: 14
    multi-ecosystem-group: all-dependencies

  - package-ecosystem: gitsubmodule
    directory: /
    open-pull-requests-limit: 1
    patterns:
      - "*"
    cooldown:
      default-days: 14
    multi-ecosystem-group: all-dependencies
