[platformio]
default_envs = watch_dev
src_dir = main
test_dir = test

[watch_base]
platform = platformio/espressif32@6.13.0
framework = espidf
board = esp32-s3-devkitc-1
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_upload.after_reset = watchdog_reset
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

[env:watch_dev]
extends = watch_base
build_flags = -DCHATESP_DEVELOPMENT_MODE=1

[env:watch_prod]
extends = watch_base
build_flags = -DCHATESP_DEVELOPMENT_MODE=0

[env:native]
platform = platformio/native@1.2.1
test_framework = unity
test_build_src = false
lib_compat_mode = off
